### ISSUE TITLE
UI flickering and shifting up/down when opening the queue panel (Mac)

### ISSUE THREAD

**Issue by Jxyme** [kyrie25/spicetify-queue-panel#1]
Hi there, I'm experiencing some UI glitches when using your extension on Mac. From what I can see, the issue(s) aren't apparent in the previews you have attached in the [README](https://github.com/kyrie25/spicetify-queue-panel#readme), so I expect this is a bug on the Spotify for Mac application, given the previews are from a Windows machine.

I've tried disabling all but Queue Panel, and even a fresh install of Spicetify.. however that unfortunately hasn't improved things.

https://github.com/kyrie25/spicetify-queue-panel/assets/43247281/43c7cd37-92a0-4d4b-8cac-ac77aab4d7c0

I have outlined the apps, extensions, snippets, and the versioning for both Spotify and Spicetify that I have installed below:

### Apps
- [Marketplace](https://github.com/spicetify/spicetify-marketplace)

### Extensions
- [Hide Podcasts](https://github.com/theRealPadster/spicetify-hide-podcasts)
- [Image Opener](https://github.com/Tetrax-10/Spicetify-Extensions/tree/master/Image-Opener)
- [Spotify Genres](https://github.com/Tetrax-10/Spicetify-Extensions/tree/master/Spotify-Genres)
- [Play Next](https://github.com/daksh2k/Spicetify-stuff/blob/master/Extensions/playNext.js)
- [Volume Percentage](https://github.com/daksh2k/Spicetify-stuff/blob/master/Extensions/volumePercentage.js)
- [Queue Time](https://github.com/Theblockbuster1/spicetify-extensions/tree/main/QueueTime)
- [Cover Ambience](https://github.com/Theblockbuster1/spicetify-extensions/tree/main/CoverAmbience)
- Queue Panel (this extension)

### Snippets
```css
/* === GLOBAL STYLES === */

/* remove X plays for single, EP, and album tracks (including "Plays" header) */
.main-trackList-playsHeader, .main-trackList-rowPlayCount {
    display: none !important;
}

/* === ARTIST PAGES === */

/* remove X monthly listeners from banner (still visible in the footer) */
.main-entityHeader-detailsText:last-child {
    display: none !important;
}
/* remove popular tracks, artist picks, etc */
.artist-artistOverview-artistOverviewContainer {
    display: none !important;
}
/* fix spacing after removal of popular tracks, artist picks, etc */
.artist-artistOverview-artistOverviewContent > div.contentSpacing > section:nth-child(2) {
    margin-top: 7px !important;
}

/* === NOW PLAYING BAR === */

/* remove lyrics button */
.main-nowPlayingBar-extraControls [aria-label="Lyrics"] {
    display: none !important;
}
/* remove full-screen button */
.main-nowPlayingBar-extraControls [aria-label="Full screen"] {
    display: none !important;
}
```

### Application Info
- Spotify for macOS (Apple Silicon)
- 1.2.15.828.g79f41970
- Spicetify v2.20.3

---

If there's any other information that'll be helpful, please let me know, and I'll see what I can do (I didn't see an issue template).

Thank you for creating this extension ◡̈ - I was honestly disappointed, but not surprised, to see Spotify had overlooked this feature.
